### ISSUE TITLE
TODO: Zer0xFF

### ISSUE THREAD

**Issue by Zer0xFF** [gytdau/openbook#3]
- [x] managing parser iterations
- [x] Pipeline S3 bucket (uploading to S3, parsing and uploading to postgres, potentially from EC3)
- [ ] unique chapter slug
- [ ] remove random book slug (aka make them reproducable) 
- [ ] Full search
- [x] Google Analyistics
